spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: jerry
    password: rkskek1
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

server:
  port: 8081
